### ISSUE TITLE
/projects 화면 구성(After Sync)

### ISSUE THREAD

**Issue by jwbaeck** [teamblend3/blend-dta-server#30]
## UI
<img width="1025" alt="스크린샷 2024-01-31 오후 11 04 23" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/c65486f2-dd05-4948-8c05-14972545af16">

## Server API
`GET` [`/api/projects`](https://github.com/teamblend3/blend-dta-server/issues/8#issue-2104921550)

## TODO
- [ ] 동기화에 성공했다면 사용자의 MongoDB 데이터를 Projects 리스트에 보여주어야 한다.
- [ ] 각 Project 항목을 클릭할 수 있어야 하며, 클릭 시 해당 Project 상세 페이지(/projects/:projectId) 로 이동해야 한다.
- [ ] Google Spread Sheet 상의 사용자 수정 내역을 보여주는 Logs 리스트가 생성되어야 한다.
- [ ] Logs 리스트는 수정이 발생한 Project 의 제목,  Project 의 ID, 수정 내용, 수정 시간 정보를 포함해야 한다.
- [ ] Google Spread Sheet 단 사용자 데이터 수정이 이루어진 이후 Projects 페이지의 새로고침 버튼을 클릭 시, 데이터 변경 내용에 대한 정보가 Logs List 에 보여져야 한다.
- [ ] Test 파일을 작성해야 한다.
