### ISSUE TITLE
홈 화면 구성

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-server#33]
## UI
<img width="1023" alt="스크린샷 2024-01-31 오후 7 08 27" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/3ad5ae25-b0e3-4b6e-a3c0-132ca853dedb">
<br/>

## TODO
- [ ] 헤더에는 화면 모드 설정(Light / Dark) 버튼과 login 버튼이 보여져야 한다.
- [ ] login 버튼 클릭 시, 로그인 페이지(/login) 로 이동할 수 있어야 한다.
- [ ] Mongo DB 로고, Google Spread Sheet Service 로고, 이 둘의 연동을 표현하는 이미지가 보여져야 한다.
- [ ] 서비스명과 서비스에 대한 설명이 보여져야 한다.
- [ ] Test 파일을 작성해야 한다.
