### ISSUE TITLE
/login 로그인 화면 구성

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-server#35]
## UI
<img width="1024" alt="스크린샷 2024-01-31 오후 7 10 52" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/5208a75f-7b61-42cc-8263-b3d1286f6518">
<img width="1023" alt="스크린샷 2024-01-31 오후 7 11 50" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/e7a562c3-db50-4e0d-8c6e-586fca860712">
<img width="1021" alt="스크린샷 2024-01-31 오후 7 30 32" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/90f5a2fa-3edc-4604-8309-0d3d13c37fa0">
<br/>

## Server API
`GET` [`/api/users/login`](https://github.com/teamblend3/blend-dta-server/issues/5#issue-2104917408)

## TODO
- [ ] 구글 소셜 로그인 버튼이 보여져야 한다.
- [ ] 로그인 버튼 클릭 시, 구글 소셜 로그인 모달창을 보여주어야 한다.
- [ ] 로그인에 성공할 시, /projects 로 이동해야 한다.
- [ ] Test 파일을 작성해야 한다.
