### ISSUE TITLE
/projects/:projectId 화면 구성(Collection Schema)

### ISSUE THREAD

**Issue by hsj2955** [teamblend3/blend-dta-server#36]
## UI
<img width="1024" alt="스크린샷 2024-01-31 오후 8 01 47" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/14c5410b-069f-403c-bd38-bd8c7208036b">
<img width="1025" alt="스크린샷 2024-01-31 오후 8 01 59" src="https://github.com/teamblend3/blend-dta-client/assets/99715151/99088950-fbae-4420-bd5b-90de0c205a7d">

## Server API
`GET` [`/api/projects/{id}`](https://github.com/teamblend3/blend-dta-server/issues/9#issue-2104927968)

## TODO
- [ ] 헤더 우측에는 프로필 이미지를 보여주어야 한다.
- [ ] 해당 Project 내의 collection 을 선택할 수 있는 select box 가 보여져야 한다.
- [ ] collection 을 선택하고 select 버튼 클릭 시, 해당 collection 의 데이터 정보가 하단에 리스트로 보여져야 한다.
- [ ] 리스트에서 각 Collection 의 Schema 구조를 확인할 수 있어야 한다.
- [ ] 사용자가 선택한 Collection 의 데이터 정보를 보여주므로, 다른 Collection 을 선택하면 해당 데이터가 보여져야 한다.
- [ ] 페이지 우측 상단에는 Project Data 내용을 새로고침 할 수 있는 버튼이 보여져야 한다.
- [ ] 사용자가 데이터를 수정한 이후 새로고침 버튼을 클릭 시, 사용자 수정 내용을 바탕으로 리스트 내용이 그에 맞게 변경되어야 한다.
- [ ] Test 파일을 작성해야 한다.
