### ISSUE TITLE
유저 프로파일 정보 다루기 (/api/users/:userId)

### ISSUE THREAD

**Issue by teamblend** [teamblend3/blend-dta-server#6]
## API Endpoint
`GET /api/users/:userId`

## TODO
1. 사용자 Profile 데이터 가져오기
- [x] ObjectId validate 를 확인하여, 에러 핸들링을 구현해야 한다.
- [x] middleware를 통하여 jwt 검사하여 가입되어 있는 유저 인지 확인
- [x] 유저에 해당하는 유저 정보를 반환한다.
- [ ] 테스트 파일 작성

## Request
```js
    headers: {
      "Authorization": jwtToken,
    }
  ```
  
## Response
- Success
```json
{
  "successs": true
  "userInfo": {
    "email": "example@google.com",
    "username": "exampleName",
    "avatarUrl": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com"
    "projects": ["5a9427648b0beebeb69579f5", "5a9427648b0beebeb69579e7", "5a9427648b0beebeb6957a21"]
  }
}
```
- Failure
```json
{
  "result": "error",
  "error" : {
    "message": "Unauthorized"
    "code": 401
  }
}
```

```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error", 
    "code": 500,
  }
}
```

## API Endpoint
`PUT /api/users/:userId`

## TODO
2. 사용자 Profile 데이터 수정하기
- [ ] 본인 프로필 페이지에서 현재 프로필 이미지를 클릭 시 프로필 이미지를 변경 가능하다.

## Request
```json
{
  "avartarURL": "somethingNewProfileImageUrl",
}
```

## response
- Success
```json
{
  "success": true,
}
```
- Failure
```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error", 
    "code": 500,
  }
}
```
