### ISSUE TITLE
프로젝트들 가져오기(/api/users/:userId/projects)

### ISSUE THREAD

**Issue by teamblend** [teamblend3/blend-dta-server#8]
## API Endpoint
`GET /api/users/:userId/projects`

## TODO
- [x] login 된 유저인지 확인
- [x] user의 아이디가 ObjectId인지 여부를 확인한 후 진행
- [x] user의 projects를 찾아서 populate하여 필요한 정보를 가져옴
- [ ] 테스트 파일 작성

## Response

- Success
```json
  {
    "success": true
    "result" : {
      "projects":[
        {
          "_id": {
            "$oid": "5a9427648b0beebeb69579e7"
          },
          "name": "Mercedes Tyler",
          "email": "mercedes_tyler@fakegmail.com",
          "movie_id": {
            "$oid": "573a1390f29313caabcd4323"
          },
          "text": "Eius veritatis vero facilis quaerat fuga temporibus. Praesentium expedita sequi repellat id. Corporis minima enim ex. Provident fugit nisi dignissimos nulla nam ipsum aliquam.",
          "date": {
            "$date": "2002-08-18T04:56:07.000Z"
          }
        },
        {
          "_id": {
            "$oid": "5a9427648b0beebeb69579f5"
          },
          "name": "John Bishop",
          "email": "john_bishop@fakegmail.com",
          "movie_id": {
            "$oid": "573a1390f29313caabcd446f"
          },
          "text": "Id error ab at molestias dolorum incidunt. Non deserunt praesentium dolorem nihil. Optio tempora vel ut quas.\nMinus dicta numquam quasi. Rem totam cumque at eum. Ullam hic ut ea magni.",
          "date": {
            "$date": "1975-01-21T00:31:22.000Z"
          }
        },
      ]
    }
  }
```

- Failure
```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error", 
    "code": 500,
  }
}
```
