### ISSUE TITLE
프로젝트 가져오기(/api/projects/:projectId)

### ISSUE THREAD

**Issue by teamblend** [teamblend3/blend-dta-server#9]
## API Endpoint
`GET /api/projects/:projectId`

## TODO
- [x] login 된 유저인지 확인
- [x] project의 아이디가 ObjectId인지 여부를 확인한 후 진행
- [x] project의 host와 userid가 같지 않으면 에러 반환
- [x] project에서 projectId에 해당하는 데이터 가져옴
- [x] 테스트 파일

## Response
- Success
```json
  {
    "success": true
    "result" : {
      "projects":
          {
            "_id": {
              "$oid": "5a9427648b0beebeb69579e7"
            },
            "name": "Mercedes Tyler",
            "email": "mercedes_tyler@fakegmail.com",
            "movie_id": {
              "$oid": "573a1390f29313caabcd4323"
            },
            "text": "Eius veritatis vero facilis quaerat fuga temporibus. Praesentium expedita sequi repellat id. Corporis minima enim ex. Provident fugit nisi dignissimos nulla nam ipsum aliquam.",
            "date": {
              "$date": "2002-08-18T04:56:07.000Z"
            }
         }
    }
  }
```

- Failure
  1. project의 id와 user id가 같지 않은 경우
```json
{
  "result": "error",
  "error": {
    "message": "Forbidden", 
    "code": 403,
  }
}
```

```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error", 
    "code": 500,
  }
}
```

## Collection 데이터
- [ ] projectId 에 해당하는 데이터를 가져와 저장되어 있는 상태
- [ ] 사용자가 특정 Collection Name 을 선택하고 버튼을 누르면 저장되어있는 데이터 중 필터링 진행 후 사용자 화면에 데이터 표시
- [ ] 다른 Collection Name 을 선택하면 같은 방법으로 저장되어 있는 데이터 내에서 추출

## JSON & Excel 파일 생성
- [ ] 사용자는 Collection 데이터 중 원하는 필드 선택하여 데이터 추출 가능해야 함
- [ ] 저장되어있는 Collection 데이터의 key 와 사용자가 선택한 필드값 비교 진행
- [ ] 일치하는 항목에 대한 데이터 추출 로직 작성
- [ ] 추출된 데이터에 대한 JSON & Excel 파일 생성 로직 작성
- [ ] 이 과정을 거치더라도 사용자의 MongoDB 상 데이터의 값은 변경되지 않음
